# Install Pytorch

url:　https://pytorch.org/get-started/locally/

In [3]:
import torch as t
print(t.__version__)

1.12.1


# Create Tensor

In [4]:
import torch as t
import numpy as np
a = t.Tensor([[1,2,3],[4,5,6]])
a_numpy = a.numpy()
a_list = a.tolist()

b = np.array([[3,2,1],[1,2,3]])
a_tensorf= t.from_numpy(b)

print(a)
print(a.numel())
print(a_numpy)
print(a_list)
print(a_tensorf)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
6
[[1. 2. 3.]
 [4. 5. 6.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor([[3, 2, 1],
        [1, 2, 3]], dtype=torch.int32)


In [5]:
import torch as t
x1 = t.zeros(3,2)
x2 = t.ones(4,3)
x3 = t.arange(1, 6)
x4 = t.linspace(0, 10, 5)
x5 = t.randn(2, 3)
x6 = t.randperm(5) # 0,1,2,3,4 洗牌
x7 = t.eye(2, 3)


print('x1: {}'.format(x1.numpy()))
print('x2: {}'.format(x2.numpy()))
print('x3: {}'.format(x3.numpy()))
print('x4: {}'.format(x4.numpy()))
print('x5: {}'.format(x5.numpy()))
print('x6: {}'.format(x6.numpy()))
print('x7: {}'.format(x7.numpy()))

x1: [[0. 0.]
 [0. 0.]
 [0. 0.]]
x2: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
x3: [1 2 3 4 5]
x4: [ 0.   2.5  5.   7.5 10. ]
x5: [[-0.99025804 -0.15802729  0.6870781 ]
 [-0.7288495   0.28516218 -1.2076206 ]]
x6: [3 2 0 4 1]
x7: [[1. 0. 0.]
 [0. 1. 0.]]


# Basic Operation

In [6]:
import torch as t
x = t.Tensor([[12,15],[3,4]])
y = t.Tensor([[5,6],[7,8]])

sum_num = x + y
sub_num = x - y
mul_num = x * y
div_num = x / y
mod_num = x % y
neg_num = -x

print('sum_num: {}'.format(sum_num.numpy()))
print('sub_num: {}'.format(sub_num.numpy()))
print('mul_num: {}'.format(mul_num.numpy()))
print('div_num: {}'.format(div_num.numpy()))
print('mod_num: {}'.format(mod_num.numpy()))
print('neg_num: {}'.format(neg_num.numpy()))



sum_num: [[17. 21.]
 [10. 12.]]
sub_num: [[ 7.  9.]
 [-4. -4.]]
mul_num: [[60. 90.]
 [21. 32.]]
div_num: [[2.4        2.5       ]
 [0.42857143 0.5       ]]
mod_num: [[2. 3.]
 [3. 4.]]
neg_num: [[-12. -15.]
 [ -3.  -4.]]


In [7]:
import torch as t
x = t.Tensor([[12,15],[3,4]])
y = t.Tensor([[5,6],[7,8]])

sum_num = t.add(x, y)
sub_num = t.subtract(x, y)
mul_num = t.multiply(x, y)
div_num = t.divide(x, y)
mod_num = t.remainder(x,y)
neg_num = t.negative(x)

print('sum_num: {}'.format(sum_num.numpy()))
print('sub_num: {}'.format(sub_num.numpy()))
print('mul_num: {}'.format(mul_num.numpy()))
print('div_num: {}'.format(div_num.numpy()))
print('mod_num: {}'.format(mod_num.numpy()))
print('neg_num: {}'.format(neg_num.numpy()))

sum_num: [[17. 21.]
 [10. 12.]]
sub_num: [[ 7.  9.]
 [-4. -4.]]
mul_num: [[60. 90.]
 [21. 32.]]
div_num: [[2.4        2.5       ]
 [0.42857143 0.5       ]]
mod_num: [[2. 3.]
 [3. 4.]]
neg_num: [[-12. -15.]
 [ -3.  -4.]]


# Matrix Operation

In [8]:
import torch as t
x1 = t.randn(2, 3)
x2 = t.randn(3, 3)

matrix_product = t.mm(x1, x2) # 矩陣相乘
matrix_inv = t.inverse(x2) # 逆運算
matrix_trans = t.transpose(x1,0, 1) # 行列對調

print(matrix_product)
print(matrix_inv)
print(matrix_trans)



tensor([[ 1.6186, -0.3720, -0.3310],
        [ 0.2823,  0.7218, -2.2301]])
tensor([[-1.3382,  1.3895, -1.6067],
        [-2.4899,  4.4647, -5.0102],
        [-0.6420,  1.2979, -2.4253]])
tensor([[-1.0272, -0.7432],
        [ 0.1584,  0.7205],
        [ 0.0661,  1.3388]])


# Tensor Type  


| Data type                | dtype                             | CPU tensor                                                   | GPU tensor                |
| ------------------------ | --------------------------------- | ------------------------------------------------------------ | ------------------------- |
| 32-bit floating point    | `torch.float32` or `torch.float`  | `torch.FloatTensor`                                          | `torch.cuda.FloatTensor`  |
| 64-bit floating point    | `torch.float64` or `torch.double` | `torch.DoubleTensor`                                         | `torch.cuda.DoubleTensor` |
| 16-bit floating point    | `torch.float16` or `torch.half`   | `torch.HalfTensor`                                           | `torch.cuda.HalfTensor`   |
| 8-bit integer (unsigned) | `torch.uint8`                     | [`torch.ByteTensor`](https://pytorch.org/docs/stable/tensors.html#torch.ByteTensor) | `torch.cuda.ByteTensor`   |
| 8-bit integer (signed)   | `torch.int8`                      | `torch.CharTensor`                                           | `torch.cuda.CharTensor`   |
| 16-bit integer (signed)  | `torch.int16` or `torch.short`    | `torch.ShortTensor`                                          | `torch.cuda.ShortTensor`  |
| 32-bit integer (signed)  | `torch.int32` or `torch.int`      | `torch.IntTensor`                                            | `torch.cuda.IntTensor`    |
| 64-bit integer (signed)  | `torch.int64` or `torch.long`     | `torch.LongTensor`                                           | `torch.cuda.LongTensor`   |
  
FloatTensor ->  'float32'  

DoubleTensor -> 'float64'  

ShortTensor -> 'int16'  

IntTensor -> 'int32'  

LongTensor -> 'int64'  

In [9]:
a = t.Tensor([[1,2,3],[4,5,6]])
print(a.dtype)
a_double = a.double()   #'float64'
print(a_double.dtype)

a_int = a.int()      #'int32'
print(a_int.dtype)


torch.float32
torch.float64
torch.int32


# Common Function

In [10]:
import torch as t
x = t.Tensor([[12,-15],[3,4]])

print(t.sum(x))
print(t.mean(x))
print(t.min(x))
print(t.max(x))
print(t.abs(x))

print('======')

print(t.sum(x, dim=0))
print(t.mean(x, dim=0))


tensor(4.)
tensor(1.)
tensor(-15.)
tensor(12.)
tensor([[12., 15.],
        [ 3.,  4.]])
tensor([ 15., -11.])
tensor([ 7.5000, -5.5000])


In [11]:
x = t.Tensor([[1.1, 2.2, 3.3],[4.5, 3.2, 2.1], [5, 0, -2]])
print(t.argmax(x, dim=0))
print(t.argmin(x, dim=0))
print(t.argmax(x, dim=1))
print(t.argmin(x, dim=1))

tensor([2, 1, 0])
tensor([0, 2, 2])
tensor([2, 0, 0])
tensor([0, 2, 2])


# Random 

In [12]:
import torch as t
a=t.randint(0,3,(3,2)) #3*2形狀 0-3
b=t.rand(3)
c=t.rand(3,2,dtype=t.double)
d=t.randn(4,3,dtype=t.double) # 高斯常態分佈

print(a,a.dtype)
print(b,b.dtype)
print(c,c.dtype)
print(d,d.dtype)

tensor([[1, 2],
        [1, 1],
        [1, 1]]) torch.int64
tensor([0.9915, 0.8603, 0.0479]) torch.float32
tensor([[0.7480, 0.4521],
        [0.3486, 0.0226],
        [0.4164, 0.7220]], dtype=torch.float64) torch.float64
tensor([[-0.7488, -1.8626,  3.4863],
        [ 1.3063, -0.5515,  0.2597],
        [-1.0984, -0.1756, -1.6848],
        [-0.7209, -0.8977, -0.9230]], dtype=torch.float64) torch.float64


# index and slicing

In [13]:
x = t.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[0,0])
print(x[0,1])
print(x[1,:])
print(x[:,2])

tensor(1.)
tensor(2.)
tensor([4., 5., 6.])
tensor([3., 6., 9.])


# reshape & flatten

In [14]:
import torch as t
x =  t.Tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,1]
])
print(x.shape)
print(x.reshape([2,6]))
print(x.reshape([2,-1]))
print(x.reshape([2,3,-1]))

# view V.S. reshape (另一種寫法)
# ref: https://www.codenong.com/cs105381089/
print('==========')
print(x.view([2,6]))
print(x.view([2,-1]))
print(x.view([2,3,-1]))

print('==========')
print(x.flatten())

torch.Size([3, 4])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11.,  1.]]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.,  1.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11.,  1.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  1.])


In [15]:
x =  t.Tensor([
    [1,2],
    [5,6],

])
print(x.is_contiguous()) # 是否連續
print(x.reshape([1,4]))
print(x.view([1,4]))


True
tensor([[1., 2., 5., 6.]])
tensor([[1., 2., 5., 6.]])


In [16]:
x = x.permute(1,0)
print(x.is_contiguous())
print(x.reshape([1,4]))
print(x.view([1,4]))


False
tensor([[1., 5., 2., 6.]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

# Squeeze & Unsqueeze

In [17]:
x = t.Tensor([1,2,3,4,5,6])
y = x.unsqueeze(dim=0)
z = x.unsqueeze(dim=1)

print(x.shape)
print(y.shape)
print(z.shape)
print('======')

x = t.Tensor([[[1,2,3],[4,5,6]]])
y = x.squeeze(dim=0)
z = x.squeeze(dim=2)
print(x.shape)
print(y.shape)
print(z.shape) # 只會擠掉 數字為1的維度


torch.Size([6])
torch.Size([1, 6])
torch.Size([6, 1])
torch.Size([1, 2, 3])
torch.Size([2, 3])
torch.Size([1, 2, 3])



# Activation Function  
![activation](./images/activation.png)

In [37]:
x = t.Tensor([[1,-2,3],[-4,5,6]])
sig_result = t.sigmoid(x)
tanh_result = t.tanh(x)
relu_result = t.relu(x)

print(sig_result)
print(tanh_result)
print(relu_result)

tensor([[0.7311, 0.1192, 0.9526],
        [0.0180, 0.9933, 0.9975]])
tensor([[ 0.7616, -0.9640,  0.9951],
        [-0.9993,  0.9999,  1.0000]])
tensor([[1., 0., 3.],
        [0., 5., 6.]])


# Dataset/DataLoader  
 
- `__getitem__`：返回一個數據樣本(`obj[index]`等價於`obj.__getitem__(index)`)
- `__len__`：返回樣本的數量(`len(obj)`等價於`obj.__len__()`)    

In [15]:
import torch
from torch.utils.data import Dataset, DataLoader, TensorDataset
BATCH_SIZE = 5

x = torch.linspace(1, 10, 10)
y = torch.linspace(11, 20, 10)

print(x)
print(y)

torch_dataset = TensorDataset(x, y)
loader = DataLoader(dataset=torch_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0 ) # num_worker= 核心數

for epoch in range(10):
    for step, (batch_x, batch_y) in enumerate(loader):
        print('Epoch: ', epoch, '| Step: ', step, '| batch x: ', batch_x.numpy(), '| batch y: ', batch_y.numpy())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])
Epoch:  0 | Step:  0 | batch x:  [ 2. 10.  9.  4.  7.] | batch y:  [12. 20. 19. 14. 17.]
Epoch:  0 | Step:  1 | batch x:  [3. 1. 6. 8. 5.] | batch y:  [13. 11. 16. 18. 15.]
Epoch:  1 | Step:  0 | batch x:  [ 1.  3.  7.  4. 10.] | batch y:  [11. 13. 17. 14. 20.]
Epoch:  1 | Step:  1 | batch x:  [2. 6. 9. 8. 5.] | batch y:  [12. 16. 19. 18. 15.]
Epoch:  2 | Step:  0 | batch x:  [4. 3. 6. 7. 8.] | batch y:  [14. 13. 16. 17. 18.]
Epoch:  2 | Step:  1 | batch x:  [ 5.  1.  9. 10.  2.] | batch y:  [15. 11. 19. 20. 12.]
Epoch:  3 | Step:  0 | batch x:  [6. 1. 9. 4. 3.] | batch y:  [16. 11. 19. 14. 13.]
Epoch:  3 | Step:  1 | batch x:  [ 5.  8. 10.  2.  7.] | batch y:  [15. 18. 20. 12. 17.]
Epoch:  4 | Step:  0 | batch x:  [9. 6. 1. 3. 2.] | batch y:  [19. 16. 11. 13. 12.]
Epoch:  4 | Step:  1 | batch x:  [ 5.  4.  8.  7. 10.] | batch y:  [15. 14. 18. 17. 20.]
Epoch:  5 | Step:

In [47]:
import os
import numpy as np
import pandas as pd
from torch.utils.data import Dataset, DataLoader

class Mydataset(Dataset):

    def __init__(self):
        """
        return a single data and a corresponding single label
        """
        df = pd.read_csv('./dataset/pima-indians-diabetes.csv')
        #print(df.head(3))
        
        self.labels = df['label']
        self.dataset = df.drop('label', axis=1)
        
        self.labels = np.asarray(self.labels)
        self.dataset = np.asarray(self.dataset)
        
        #print(self.labels[:5])        
        #print(self.dataset[:5])
        
        ## add normalization to here if you want
        
        
    def __getitem__(self, index):
        """
        return a single data and a corresponding single label
        """

        
        return self.dataset[index], self.labels[index]

    def __len__(self):
        """
        return total data length
        """
        
        return len(self.dataset)
my_data = Mydataset()
data, label = my_data[0]

print(data)
print(label)

'''
for data, label in my_data:
    print(data)
    print(label)
    print('===')
'''

my_data_loader = DataLoader(my_data, batch_size=5, shuffle=True)

for batch_data, batch_labels in my_data_loader:
    print(batch_data.shape)
    print(batch_labels.shape)
    print(batch_data)
    print(batch_labels)
    
    break

[  6.    148.     72.     35.      0.     33.6     0.627  50.   ]
1
torch.Size([5, 8])
torch.Size([5])
tensor([[3.0000e+00, 1.9300e+02, 7.0000e+01, 3.1000e+01, 0.0000e+00, 3.4900e+01,
         2.4100e-01, 2.5000e+01],
        [2.0000e+00, 8.8000e+01, 7.4000e+01, 1.9000e+01, 5.3000e+01, 2.9000e+01,
         2.2900e-01, 2.2000e+01],
        [7.0000e+00, 1.4700e+02, 7.6000e+01, 0.0000e+00, 0.0000e+00, 3.9400e+01,
         2.5700e-01, 4.3000e+01],
        [3.0000e+00, 1.7300e+02, 8.4000e+01, 3.3000e+01, 4.7400e+02, 3.5700e+01,
         2.5800e-01, 2.2000e+01],
        [1.0000e+00, 1.9900e+02, 7.6000e+01, 4.3000e+01, 0.0000e+00, 4.2900e+01,
         1.3940e+00, 2.2000e+01]], dtype=torch.float64)
tensor([1, 0, 1, 1, 1])


# Gradient
微分
一定要requires_grad = ture 才會被微分

In [45]:
import torch
x = torch.ones((1,))
print(x.requires_grad)

x = torch.ones((1,), requires_grad=True)
print(x.requires_grad)

y = torch.zeros((1,))
print(y.requires_grad)

z = 2*x + y             # x可以微 ， y不可以微，相加之後的z可以微。
print(z.requires_grad)

y.requires_grad_(True)
print(y.requires_grad)

False
True
False
True
True


In [18]:
import torch

x = torch.ones((1,), requires_grad=True)
y = 2*x*x - x + 3
y.backward() # 對y裡面所有可微的數字，做偏微。
print(x.grad)  


tensor([3.])


In [19]:
import torch

x = torch.Tensor([[1,2,3],[4,5,6]])
x.requires_grad_(True)
y = 2*x*x - x + 3
y.backward(torch.ones(2,3)) #裡面都是1 ;*1
print(x.grad)

tensor([[ 3.,  7., 11.],
        [15., 19., 23.]])


In [18]:
import torch

x = torch.Tensor([[1,2,3],[4,5,6]])
x.requires_grad_(True)
y = 2*x*x - x + 3
y.backward(torch.ones(2,3)+1) #裡面都變2了 ;*2
print(x.grad)

tensor([[ 6., 14., 22.],
        [30., 38., 46.]])


$$
y = x^2\bullet e^x
$$

$$
{dy \over dx} = 2x\bullet e^x + x^2 \bullet e^x
$$

In [17]:
def f(x):
    y = x**2 * t.exp(x)
    return y

def gradf(x): 
    dx = 2*x*t.exp(x) + x**2*t.exp(x)
    return dx

x = t.randn(3,4, requires_grad = True)
y = f(x)

y.backward(t.ones(y.size())) 
print(x.grad)
print(gradf(x)) 

tensor([[-0.4434, -0.4146,  0.5804,  6.6260],
        [-0.4611, -0.1204, -0.4467,  1.5245],
        [-0.2429,  3.7458, 13.3933, -0.4415]])
tensor([[-0.4434, -0.4146,  0.5804,  6.6260],
        [-0.4611, -0.1204, -0.4467,  1.5245],
        [-0.2429,  3.7458, 13.3933, -0.4415]], grad_fn=<AddBackward0>)


# Optimization 

In [46]:
import torch

learning_rate = 0.1

x = torch.ones((1,), requires_grad=True)

optimizer = torch.optim.SGD([x], lr=learning_rate)
#optimizer = torch.optim.RMSprop([x], lr=learning_rate, alpha=0.9)
#optimizer = torch.optim.Adam([x], lr=learning_rate, betas=(0.9, 0.99))


for i in range(1000):
    y = 2*x*x-x+3
    
    optimizer.zero_grad() #清空優化器
    y.backward()
    optimizer.step()
print(x)

tensor([0.2500], requires_grad=True)
